# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera/camera_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'camera/camera_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from camera import camera_messages_pb2 as camera_dot_camera__messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63\x61mera/camera_service.proto\x12\x06\x63\x61mera\x1a\x1c\x63\x61mera/camera_messages.proto\x1a\x1bgoogle/protobuf/empty.proto2\xe8\x01\n\rCameraService\x12M\n\x11\x43hangeCameraIndex\x12 .camera.ChangeCameraIndexRequest\x1a\x16.google.protobuf.Empty\x12G\n\x0e\x41\x64\x64\x43\x61meraIndex\x12\x1d.camera.AddCameraIndexRequest\x1a\x16.google.protobuf.Empty\x12?\n\rRemoveCameras\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB&\xaa\x02#MotionCapture.Grpc.Contracts.Camerab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera.camera_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#MotionCapture.Grpc.Contracts.Camera'
  _globals['_CAMERASERVICE']._serialized_start=99
  _globals['_CAMERASERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
