# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera/camera_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'camera/camera_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63\x61mera/camera_messages.proto\x12\x06\x63\x61mera\"-\n\x15\x41\x64\x64\x43\x61meraIndexRequest\x12\x14\n\x0c\x63\x61mera_Index\x18\x01 \x01(\x05\"S\n\x18\x43hangeCameraIndexRequest\x12\x1d\n\x15previous_camera_Index\x18\x01 \x01(\x05\x12\x18\n\x10new_camera_Index\x18\x02 \x01(\x05\x42&\xaa\x02#MotionCapture.Grpc.Contracts.Camerab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera.camera_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#MotionCapture.Grpc.Contracts.Camera'
  _globals['_ADDCAMERAINDEXREQUEST']._serialized_start=40
  _globals['_ADDCAMERAINDEXREQUEST']._serialized_end=85
  _globals['_CHANGECAMERAINDEXREQUEST']._serialized_start=87
  _globals['_CHANGECAMERAINDEXREQUEST']._serialized_end=170
# @@protoc_insertion_point(module_scope)
