# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: motion_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'motion_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import motion_messages_pb2 as motion__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14motion_service.proto\x12\x06motion\x1a\x15motion_messages.proto2O\n\rMotionService\x12>\n\rProcessMotion\x12\x15.motion.MotionRequest\x1a\x16.motion.MotionResponseB\x1f\xaa\x02\x1cMotionCapture.Grpc.Contractsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motion_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034MotionCapture.Grpc.Contracts'
  _globals['_MOTIONSERVICE']._serialized_start=55
  _globals['_MOTIONSERVICE']._serialized_end=134
# @@protoc_insertion_point(module_scope)
