# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skeleton/skeleton_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'skeleton/skeleton_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from skeleton import skeleton_messages_pb2 as skeleton_dot_skeleton__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fskeleton/skeleton_service.proto\x12\x08skeleton\x1a skeleton/skeleton_messages.proto2T\n\x0fSkeletonService\x12\x41\n\x0eStreamSkeleton\x12\x19.skeleton.SkeletonRequest\x1a\x12.skeleton.Skeleton0\x01\x42(\xaa\x02%MotionCapture.Grpc.Contracts.Skeletonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skeleton.skeleton_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002%MotionCapture.Grpc.Contracts.Skeleton'
  _globals['_SKELETONSERVICE']._serialized_start=79
  _globals['_SKELETONSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
