# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skeleton/skeleton_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'skeleton/skeleton_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n skeleton/skeleton_messages.proto\x12\x08skeleton\"\x9c\x01\n\rSkeletonJoint\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cparent_index\x18\x02 \x01(\x05\x12\r\n\x05pos_x\x18\x03 \x01(\x02\x12\r\n\x05pos_y\x18\x04 \x01(\x02\x12\r\n\x05pos_z\x18\x05 \x01(\x02\x12\r\n\x05rot_x\x18\x06 \x01(\x02\x12\r\n\x05rot_y\x18\x07 \x01(\x02\x12\r\n\x05rot_z\x18\x08 \x01(\x02\x12\r\n\x05rot_w\x18\t \x01(\x02\"I\n\x08Skeleton\x12\'\n\x06joints\x18\x01 \x03(\x0b\x32\x17.skeleton.SkeletonJoint\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\"\x11\n\x0fSkeletonRequestB(\xaa\x02%MotionCapture.Grpc.Contracts.Skeletonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skeleton.skeleton_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002%MotionCapture.Grpc.Contracts.Skeleton'
  _globals['_SKELETONJOINT']._serialized_start=47
  _globals['_SKELETONJOINT']._serialized_end=203
  _globals['_SKELETON']._serialized_start=205
  _globals['_SKELETON']._serialized_end=278
  _globals['_SKELETONREQUEST']._serialized_start=280
  _globals['_SKELETONREQUEST']._serialized_end=297
# @@protoc_insertion_point(module_scope)
