# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from skeleton import skeleton_messages_pb2 as skeleton_dot_skeleton__messages__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in skeleton/skeleton_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkeletonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSkeleton = channel.unary_stream(
                '/skeleton.SkeletonService/StreamSkeleton',
                request_serializer=skeleton_dot_skeleton__messages__pb2.SkeletonRequest.SerializeToString,
                response_deserializer=skeleton_dot_skeleton__messages__pb2.Skeleton.FromString,
                _registered_method=True)


class SkeletonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamSkeleton(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkeletonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSkeleton': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSkeleton,
                    request_deserializer=skeleton_dot_skeleton__messages__pb2.SkeletonRequest.FromString,
                    response_serializer=skeleton_dot_skeleton__messages__pb2.Skeleton.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skeleton.SkeletonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skeleton.SkeletonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkeletonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSkeleton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/skeleton.SkeletonService/StreamSkeleton',
            skeleton_dot_skeleton__messages__pb2.SkeletonRequest.SerializeToString,
            skeleton_dot_skeleton__messages__pb2.Skeleton.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
