# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calibration/calibration_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calibration/calibration_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from motion import motion_messages_pb2 as motion_dot_motion__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&calibration/calibration_messages.proto\x12\x0b\x63\x61libration\x1a\x1cmotion/motion_messages.proto\"7\n\x10\x43\x61librationFrame\x12#\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x13.motion.CameraFrame\"\xb8\x01\n\x11\x43\x61librationStatus\x12\x18\n\x10\x66rames_collected\x18\x01 \x01(\x05\x12\x17\n\x0f\x66rames_required\x18\x02 \x01(\x05\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x0f\n\x07is_done\x18\x04 \x01(\x08\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x0f\n\x07message\x18\x06 \x01(\t\x12+\n\tlandmarks\x18\x07 \x03(\x0b\x32\x18.motion.FrameLandmarks2DB+\xaa\x02(MotionCapture.Grpc.Contracts.Calibrationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calibration.calibration_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002(MotionCapture.Grpc.Contracts.Calibration'
  _globals['_CALIBRATIONFRAME']._serialized_start=85
  _globals['_CALIBRATIONFRAME']._serialized_end=140
  _globals['_CALIBRATIONSTATUS']._serialized_start=143
  _globals['_CALIBRATIONSTATUS']._serialized_end=327
# @@protoc_insertion_point(module_scope)
