# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calibration/calibration_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calibration/calibration_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from calibration import calibration_messages_pb2 as calibration_dot_calibration__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%calibration/calibration_service.proto\x12\x0b\x63\x61libration\x1a&calibration/calibration_messages.proto2d\n\x12\x43\x61librationService\x12N\n\tCalibrate\x12\x1d.calibration.CalibrationFrame\x1a\x1e.calibration.CalibrationStatus(\x01\x30\x01\x42+\xaa\x02(MotionCapture.Grpc.Contracts.Calibrationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calibration.calibration_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002(MotionCapture.Grpc.Contracts.Calibration'
  _globals['_CALIBRATIONSERVICE']._serialized_start=94
  _globals['_CALIBRATIONSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
